// Mock discovery response — shaped exactly like the real backend's
// GET /github/discovery payload (requirement_intelligence, ai_recommendation,
// best_external_candidate, external_recommendations). Swap the service layer
// in discoveryApi.js to stop using this once the backend is ready; no
// component needs to change.

function repo({
  name,
  fullName,
  description,
  language,
  stars,
  forks,
  updatedAt,
  topics,
  frameworks,
  architectures,
  technologies,
  healthStatus,
  healthPercentage,
  finalScore,
  strategy,
  reuseScore,
  requirementCoverage,
  matched,
  missing,
  risks,
  answer,
}) {
  return {
    id: fullName,
    name,
    full_name: fullName,
    description,
    language,
    stars,
    forks,
    watchers: Math.round(stars * 0.6),
    open_issues: Math.max(1, Math.round(stars * 0.01)),
    default_branch: "main",
    updated_at: updatedAt,
    created_at: "2021-03-14T00:00:00Z",
    html_url: `https://github.com/${fullName}`,
    clone_url: `https://github.com/${fullName}.git`,
    topics,
    archived: false,
    fork: false,
    analysis: {
      technologies,
      summary: description,
    },
    readme_available: true,
    repository_health: {
      health_score: healthPercentage / 100,
      health_percentage: healthPercentage,
      status: healthStatus,
    },
    architecture_intelligence: {
      frameworks,
      architectures,
      technologies,
    },
    ranking: {
      semantic_score: finalScore * 0.9,
      requirement_score: finalScore * 0.95,
      health_score: healthPercentage / 100,
      final_score: finalScore,
    },
    reuse_intelligence: {
      strategy,
      reuse_score: reuseScore,
      requirement_coverage: requirementCoverage,
      repository_health: healthPercentage,
      matched_requirements: matched,
      missing_requirements: missing,
      risks,
    },
    ai_answer: answer,
  };
}

export function buildMockDiscoveryResponse(query) {
  const best = repo({
    name: "orbit-dash",
    fullName: "hpe-oss/orbit-dash",
    description:
      "A real-time analytics dashboard starter with charting, dark mode, and role-based access — built on React 18 and FastAPI.",
    language: "TypeScript",
    stars: 4210,
    forks: 512,
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 6).toISOString(),
    topics: ["dashboard", "react", "fastapi", "analytics", "dark-mode"],
    frameworks: ["React", "FastAPI", "Recharts"],
    architectures: ["Layered API", "Component-driven UI"],
    technologies: ["React", "TypeScript", "FastAPI", "PostgreSQL", "Docker"],
    healthStatus: "excellent",
    healthPercentage: 91,
    finalScore: 0.88,
    strategy: "reuse_directly",
    reuseScore: 86,
    requirementCoverage: 82,
    matched: ["real-time updates", "authentication", "dark theme", "charting"],
    missing: ["multi-tenant support"],
    risks: ["No first-party mobile layout"],
    answer:
      "This repository already implements the real-time dashboard, dark-mode UI, and role-based access your requirements describe, with an actively maintained FastAPI backend. Reusing it directly would save the most time; you'd mainly need to add multi-tenant support on top.",
  });

  const alternatives = [
    repo({
      name: "pulse-metrics",
      fullName: "opensource-labs/pulse-metrics",
      description: "Lightweight metrics dashboard with pluggable data sources and a minimal footprint.",
      language: "JavaScript",
      stars: 1830,
      forks: 201,
      updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 20).toISOString(),
      topics: ["metrics", "dashboard", "react"],
      frameworks: ["React", "Express"],
      architectures: ["Plugin-based"],
      technologies: ["React", "Express", "SQLite"],
      healthStatus: "healthy",
      healthPercentage: 74,
      finalScore: 0.71,
      strategy: "fork_and_extend",
      reuseScore: 64,
      requirementCoverage: 58,
      matched: ["charting", "dark theme"],
      missing: ["authentication", "real-time updates"],
      risks: ["Smaller community", "No built-in auth"],
      answer: "Good architectural reference for the plugin system, but missing auth and real-time updates.",
    }),
    repo({
      name: "reactive-panel",
      fullName: "civic-tools/reactive-panel",
      description: "Component library for building internal admin panels quickly, with a strong theming system.",
      language: "TypeScript",
      stars: 2670,
      forks: 340,
      updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 3).toISOString(),
      topics: ["admin-panel", "component-library", "theming"],
      frameworks: ["React", "Vite"],
      architectures: ["Component library"],
      technologies: ["React", "TypeScript", "Vite"],
      healthStatus: "healthy",
      healthPercentage: 79,
      finalScore: 0.68,
      strategy: "reuse_components",
      reuseScore: 60,
      requirementCoverage: 50,
      matched: ["dark theme", "component reuse"],
      missing: ["backend", "real-time updates"],
      risks: ["Frontend only — no backend included"],
      answer: "Strong component set to borrow from, but you'd still need to build the backend and real-time layer.",
    }),
    repo({
      name: "grafana-lite",
      fullName: "monitoring-oss/grafana-lite",
      description: "A stripped-down, self-hostable observability dashboard inspired by Grafana.",
      language: "Go",
      stars: 5890,
      forks: 610,
      updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 45).toISOString(),
      topics: ["observability", "monitoring", "self-hosted"],
      frameworks: ["Go", "Vue"],
      architectures: ["Microservice"],
      technologies: ["Go", "Vue", "InfluxDB"],
      healthStatus: "moderate",
      healthPercentage: 55,
      finalScore: 0.52,
      strategy: "architectural_reference",
      reuseScore: 41,
      requirementCoverage: 34,
      matched: ["real-time updates"],
      missing: ["React frontend", "authentication", "dark theme UI parity"],
      risks: ["Different language/stack (Go)", "Slower recent commit activity"],
      answer: "Useful as an architectural reference for the metrics pipeline, but the stack doesn't match your requirements.",
    }),
    repo({
      name: "simple-crud-ui",
      fullName: "starter-kits/simple-crud-ui",
      description: "Minimal CRUD admin scaffold — not much beyond basic tables and forms.",
      language: "JavaScript",
      stars: 320,
      forks: 45,
      updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 300).toISOString(),
      topics: ["crud", "starter"],
      frameworks: ["React"],
      architectures: ["Monolith"],
      technologies: ["React", "Express"],
      healthStatus: "weak",
      healthPercentage: 28,
      finalScore: 0.21,
      strategy: "build_new",
      reuseScore: 18,
      requirementCoverage: 12,
      matched: [],
      missing: ["real-time updates", "authentication", "dark theme", "charting"],
      risks: ["Largely inactive", "Covers almost none of the requirements"],
      answer: "Too thin to reuse meaningfully for this requirement set — better to build new.",
    }),
  ];

  return {
    query,
    requirement_intelligence: {
      mode: "llm",
      semantic_query: `${query} — expanded for semantic search across internal and external repositories`,
      specification: {
        project_type: "Analytics Dashboard",
        technologies: ["React", "FastAPI", "PostgreSQL"],
        core_capabilities: ["real-time updates", "authentication", "charting"],
        optional_capabilities: ["multi-tenant support"],
        architecture_preferences: ["Component-driven UI", "Layered API"],
      },
    },
    ai_recommendation: {
      answer: best.ai_answer,
    },
    best_external_candidate: best,
    external_recommendations: [best, ...alternatives],
  };
}
